modLoader = "javafml"
loaderVersion = "[0,)"
issueTrackerURL = "https://github.com/IAFEnvoy/Integration/issues"
license = "LGPL-3.0"

[[mods]]
modId = "integration"
version = "${version}"
displayName = "Integration"
authors = "IAFEnvoy"
description = '''
Library for better mod integrations.
'''

[[dependencies.integration]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.integration]]
modId = "minecraft"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
